services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"
